using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using MVCInternetGamesShop.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace MVCInternetGamesShop.Infrastructure
{
    public class Initializer : DropCreateDatabaseAlways<ApplicationDbContext>
    {
        protected override void Seed(ApplicationDbContext context)
        {
            SeedData(context);            
            base.Seed(context);
        }

        private static void SeedData(ApplicationDbContext context)
        {
            var games = new List<Game>
            {
                new Game () {Name="Tomb Raider", PlatformId = 1, Price = 200, IsBestseller = false, Description = "Gra z Larą Croft na PS4. Tomb Raider jest grą akcji z wątkami przygodowymi stworzoną przez studio Crystal Dynamics. W warstwie fabularnej tytuł stanowi prequel wydarzeń opisanych w pozostałych odsłonach cyklu o przygodach Lary Croft. Gracze mają okazję poznać młodość głównej bohaterki, która po katastrofie statku badawczego próbuje przetrwać na tajemniczej wyspie u wybrzeży Japonii.", ImageName="RiseOfTheTombRider.jpg", ReleaseDate= new DateTime(2015, 11, 11) },
                new Game () {Name="Tomb Raider", PlatformId = 2, Price = 220, IsBestseller = false, Description = "Gra z Larą Croft na PC. Tomb Raider jest grą akcji z wątkami przygodowymi stworzoną przez studio Crystal Dynamics. W warstwie fabularnej tytuł stanowi prequel wydarzeń opisanych w pozostałych odsłonach cyklu o przygodach Lary Croft. Gracze mają okazję poznać młodość głównej bohaterki, która po katastrofie statku badawczego próbuje przetrwać na tajemniczej wyspie u wybrzeży Japonii.", ImageName="TombRaider.jpg", ReleaseDate= new DateTime(2015, 11, 11) },
                new Game () {Name="Tomb Raider", PlatformId = 3, Price = 230, IsBestseller = false, Description = "Gra z Larą Croft na XBOX. Tomb Raider jest grą akcji z wątkami przygodowymi stworzoną przez studio Crystal Dynamics. W warstwie fabularnej tytuł stanowi prequel wydarzeń opisanych w pozostałych odsłonach cyklu o przygodach Lary Croft. Gracze mają okazję poznać młodość głównej bohaterki, która po katastrofie statku badawczego próbuje przetrwać na tajemniczej wyspie u wybrzeży Japonii.", ImageName="TombRaiderXBOX.jpg", ReleaseDate= new DateTime(2017, 07, 31) },
                new Game () {Name="Horizon Zero Dawn", PlatformId = 1, Price = 240, IsBestseller = true, Description = "Gra Horizon Zero Dawn na PS4. Trzecioosobowa gra akcji z elementami RPG, za której powstanie odpowiada znana z serii Killzone ekipa Guerrilla Games. Akcja tytułu osadzona została w odległej przyszłości, w której na skutek upadku nowoczesnej cywilizacji ludzkość cofnęła się w rozwoju, a dominujacą rolę w ekosystemie pełnią inteligentne, przypominające zwierzęta maszyny. Gracze wcielają się w postać Aloy – młodej dziewczyny pragnącej zgłębić tajemnice dawnej cywilizacji i jednocześnie poznać swoje przeznaczenie. W konfrontacji z wrogo nastawionymi maszynami bohaterka może liczyć na indywidualnie rozwijane umiejętności oraz masę broni i pułapek, stworzonych z części pokonanych przeciwników. Akcja gry toczy się w otwartym świecie, a bohaterka może decydować o kolejności i metodach realizacji kolejnych zadań. W grze możliwa jest zarówno otwarta konfrontacja z wrogiem, jak i ciche działanie z wykorzystaniem słabych punktów przeciwnika.", ImageName="HorizonZeroDawn.jpg", ReleaseDate= new DateTime(2015, 11, 11) },
                new Game () {Name="FEAR", PlatformId = 2, Price = 140, IsBestseller = true, Description = "Gra FEAR na PC. Hybryda pierwszoosobowej strzelaniny i survival horroru, opracowana przez zespół Monolith Productions. Główny bohater należy do tytułowego First Encounter Assault Recon – specjalnego oddziału antyterrorystycznego, którego członkowie przechodzą konwencjonalne szkolenie oraz zdobywają zdolności o paranormalnym charakterze. Zadaniem, jakie musi wykonać, jest odbicie siedziby korporacji technologicznej Armacham z rąk nieznanych przestępców. W trakcie zabawy w F.E.A.R.: First Encounter Assault Recon eksplorujemy zróżnicowane lokacje (akcja toczy się zarówno na zewnątrz, jak i wewnątrz zabudowań) oraz walczymy z napotkanymi przeciwnikami – w starciach robimy użytek nie tylko z rozbudowanego arsenału, lecz także z wyżej wspomnianych, nietypowych zdolności naszego podopiecznego, na czele ze spowalnianiem czasu. Element grozy zapewnia obecność Almy – tajemniczej dziewczynki odpowiedzialnej za rozgrywające się wokół nas niewytłumaczalne zjawiska. Na potrzeby gry przygotowano rozbudowany model fizyczny, a całość charakteryzuje się szczegółową oprawą graficzną.", ImageName="FEAR.jpg", ReleaseDate= new DateTime(2015, 11, 11) },
                new Game () {Name="Gears Of War", PlatformId = 3, Price = 100, IsBestseller = true, Description = "Gra Gears of War na XBOX. Futurystyczna, trzecioosobowa strzelanina, opracowana przez twórców bestsellerowej serii Unreal – firmę Epic Games. Akcja gry toczy się na przypominającej Ziemię planecie Sera, wyniszczonej długoletnią wojną o surowce. Na skutek prac poszukiwawczych na powierzchnię planety wydostały się wrogie istoty zwane Szarańczą, zabijając ok. 80 procent mieszkańców planety. 14 lat po tym wydarzeniu, kiedy sytuacja na froncie staje się beznadziejna, do walki wysłany zostaje skazany za dezercję Marcus Fenix. Mimo że akcja gry toczy się w dość szybkim tempie, spory nacisk położono na taktyczny aspekt rozgrywki i konieczność wykorzystywania rozmaitych osłon. Do dyspozycji mamy zaś szeroki arsenał futurystycznych broni oraz siłę fizyczną ciężko opancerzonego bohatera. Oprócz głównej kampanii fabularnej, gra oferuje atrakcyjne opcje zabawy wieloosobowej – w tym tryby kooperacji i rywalizacji, przeznaczone dla max. 8 graczy. O stronę wizualną zadbał zaś silnik Unreal Engine trzeciej generacji.", ImageName="GearsOfWar.jpg", ReleaseDate= new DateTime(2015, 11, 11) },
                new Game () {Name="BloodBorne", PlatformId = 1, Price = 270, IsBestseller = true, Description = "Gra BloodBorne na PS4. Klasyczne RPG akcji, stanowiące duchową kontynuację bestsellerowej serii Dark Souls oraz jej poprzedniczki, Demon’s Souls. Gra została opracowana przez twórcę wspomnianych produkcji – Hidetakiego Miyazakiego i jego studio From Software. Akcja tytułu przenosi nas do mrocznego uniwersum fantasy, utrzymanego w XIX-wiecznej, wiktoriańskiej stylistyce. Mieszkańców ponurej metropolii Yharnam dotknęła tajemnicza zaraza, zmieniająca ludzi w przerażające bestie. Celem zabawy będzie odkrycie skrywanych przez miasto tajemnic i ustalenie, kto lub co odpowiada za śmiertelną plagę. Mechanika rozgrywki nie odbiega od znanych z Dark Souls schematów, koncentrując się na zaawansowanym systemie walki, w którym prócz parowania ciosów, uników i szybkich kontrataków pojawiła się także możliwość skorzystania z broni palnej. Oprawa graficzna prezentuje wysoki poziom wykonania, a sam świat gry jest znacznie większy i bardziej otwarty, co stało się możliwe dzięki wykorzystaniu potencjału konsol nowej generacji.", ImageName="BloodBorne.jpg", ReleaseDate= new DateTime(2015, 11, 11) },
                new Game () {Name="The Sims 4", PlatformId = 2, Price = 216, IsBestseller = true, Description = "The Sims 4 – komputerowa gra symulacyjna, będąca czwartą częścią serii The Sims, w której gracze sterują życiem wirtualnych ludzi. Gra została opracowana przez firmę Maxis, a wydana przez Electronic Arts 2 września 2014 roku", ImageName="The sims 4.jpg", ReleaseDate= new DateTime(2017, 11, 11) },
                new Game () {Name="Mafia III", PlatformId = 3, Price = 244.09m, IsBestseller = true, Description = "Gra Mafia III na XBOX. Trzecia odsłona bestsellerowej serii mafijnych gier akcji, opracowana przez utworzone pod skrzydłami 2K Games studio Hangar 13, w skład którego weszli twórcy poprzednich części cyklu. Akcja gry osadzona została w 1968 roku w New Bordeaux - fikcyjnym mieście wzorowanym na Nowym Orleanie, a jej głównym protagonistą jest powracający z wojny w Wietnamie Lincoln Clay, którego mafijna rodzina została brutalnie wymordowana przez przestępczą konkurencję. W dokonaniu zemsty na sprawcach masakry, Clayowi pomagają trzej inni bossowie mafijnego półświatka, w tym znany z drugiej części gry Vito Scaletta. Pod względem rozgrywki Mafia III mocno zbliża się do konkurencyjnej serii Grand Theft Auto, oferując otwarty świat z pełną swobodą działania oraz jeszcze więcej elementów sandboksowych. Jedną z najważniejszych nowości jest możliwość przejmowania kryjówek wrogich ugrupowań, co przekłada się na szereg przydatnych bonusów. Ponadto poprawiono model jazdy samochodem i wprowadzono możliwość ostrzału z jadącego pojazdu.", ImageName="Mafia III.jpg", ReleaseDate= new DateTime(2015, 11, 11) },
                new Game () {Name="Life is strange", PlatformId = 1, Price = 254, IsBestseller = true, Description = "Gra Life is Strange na PS4. Opracowana przez znane z gry Remember Me francuskie studio DONTNOD epizodyczna gra przygodowa, wzorowana na produkcjach firmy Telltale Games. Jej bohaterką jest osiemnastoletnia Max Caulfield, która po latach powraca do rodzinnego miasteczka Arcadia Bay w Oregonie. Wraz z dawną przyjaciółką Chloe podejmuje śledztwo w sprawie tajemniczego zniknięcia Rachel Amber, co staje się początkiem serii niewytłumaczalnych zdarzeń. Kluczową rolę w grze pełni fabuła, zaś sama mechanika zabawy bazuje na sprawdzonej formule studia Telltale, łącząc możliwość swobodnej eksploracji świata z koniecznością podejmowania wyborów, mających swe konsekwencje w dalszym toku rozgrywki. W odróżnieniu od gier twórców The Walking Dead, tutaj gracz jest wręcz zachęcany do zmieniania dokonywanych wyborów - Max dysponuje mocą cofania czasu, co pozwala testować różne warianty wydarzeń bez konieczności wielokrotnego przechodzenia danego epizodu. Od strony technicznej gra stoi na wysokim poziomie; twórcy postawili na wyrazistą, pastelową oprawę graficzną i niezwykle klimatyczną ścieżkę dźwiękową.", ImageName="LifeIsStrange.jpg", ReleaseDate= new DateTime(2015, 11, 11) },
                new Game () {Name="Life is strange", PlatformId = 2, Price = 255.94m, IsBestseller = true, Description = "Gra Life is Strange na PC. Opracowana przez znane z gry Remember Me francuskie studio DONTNOD epizodyczna gra przygodowa, wzorowana na produkcjach firmy Telltale Games. Jej bohaterką jest osiemnastoletnia Max Caulfield, która po latach powraca do rodzinnego miasteczka Arcadia Bay w Oregonie. Wraz z dawną przyjaciółką Chloe podejmuje śledztwo w sprawie tajemniczego zniknięcia Rachel Amber, co staje się początkiem serii niewytłumaczalnych zdarzeń. Kluczową rolę w grze pełni fabuła, zaś sama mechanika zabawy bazuje na sprawdzonej formule studia Telltale, łącząc możliwość swobodnej eksploracji świata z koniecznością podejmowania wyborów, mających swe konsekwencje w dalszym toku rozgrywki. W odróżnieniu od gier twórców The Walking Dead, tutaj gracz jest wręcz zachęcany do zmieniania dokonywanych wyborów - Max dysponuje mocą cofania czasu, co pozwala testować różne warianty wydarzeń bez konieczności wielokrotnego przechodzenia danego epizodu. Od strony technicznej gra stoi na wysokim poziomie; twórcy postawili na wyrazistą, pastelową oprawę graficzną i niezwykle klimatyczną ścieżkę dźwiękową.", ImageName="LifeIsStrange.jpg", ReleaseDate= new DateTime(2015, 11, 11) },
                new Game () {Name="Life is strange", PlatformId = 3, Price = 256, IsBestseller = true, Description = "Gra Life is Strange na XBOX. Opracowana przez znane z gry Remember Me francuskie studio DONTNOD epizodyczna gra przygodowa, wzorowana na produkcjach firmy Telltale Games. Jej bohaterką jest osiemnastoletnia Max Caulfield, która po latach powraca do rodzinnego miasteczka Arcadia Bay w Oregonie. Wraz z dawną przyjaciółką Chloe podejmuje śledztwo w sprawie tajemniczego zniknięcia Rachel Amber, co staje się początkiem serii niewytłumaczalnych zdarzeń. Kluczową rolę w grze pełni fabuła, zaś sama mechanika zabawy bazuje na sprawdzonej formule studia Telltale, łącząc możliwość swobodnej eksploracji świata z koniecznością podejmowania wyborów, mających swe konsekwencje w dalszym toku rozgrywki. W odróżnieniu od gier twórców The Walking Dead, tutaj gracz jest wręcz zachęcany do zmieniania dokonywanych wyborów - Max dysponuje mocą cofania czasu, co pozwala testować różne warianty wydarzeń bez konieczności wielokrotnego przechodzenia danego epizodu. Od strony technicznej gra stoi na wysokim poziomie; twórcy postawili na wyrazistą, pastelową oprawę graficzną i niezwykle klimatyczną ścieżkę dźwiękową.", ImageName="LifeIsStrange.jpg", ReleaseDate= new DateTime(2015, 11, 11) },
                new Game () {Name="The Last of Us", PlatformId = 1, Price = 276, IsBestseller = true, Description = "Gra the Last of Us na PS4. Przygodowa gra akcji w konwencji postapokaliptycznego survival horroru, stworzona przez studio deweloperskie Naughty Dog (znane przede wszystkim z serii Uncharted) przy wsparciu wydawniczym firmy Sony Computer Entertainment. Akcja The Last of Us toczy się w niedalekiej przyszłości - 20 lat po tym, jak tajemnicza zaraza zdziesiątkowała ludzkość i przyczyniła się do upadku cywilizacji. Dwoje bohaterów – przemytnik Joel (w tę postać wciela się gracz) oraz nastoletnia sierota Ellie próbują przetrwać w świecie pełnym niebezpieczeństw. Rozgrywka opiera się głównie na eksplorowaniu lokacji oraz walce z przeciwnikami przy użyciu broni palnej lub elementów otoczenia (kamienie, nogi stołowe itp.). Poza kampanią trybu jednoosobowego gra oferuje również w pełni funkcjonalny, sieciowy multiplayer z dwoma wariantami zabawy - Walka o zapasy i Ocaleni.", ImageName="TheLastOfUs.jpg", ReleaseDate= new DateTime(2015, 11, 11) },
                new Game () {Name="Redeemer", PlatformId = 2, Price = 106, IsBestseller = true, Description = "Redeemer na PC. Brutalny, nasycony akcją hack’n’slash, przygotowany przez rosyjski zespół Sobaka Studio. Głównym bohaterem Redeemer jest Vasily – potężnie zbudowany mnich o burzliwej przeszłości. Jako najemnik na usługach bezwzględnej korporacji zbrojeniowej, Vasily dopuszczał się najgorszych czynów: morderstw, tortur i wymuszeń. Zdradzony przez pracodawców, zdołał uciec siepaczom korporacji i ukryć się w górskim klasztorze, gdzie wkroczył na drogę duchowej przemiany. Przeszłość jednak nie dała o sobie zapomnieć. Agenci korporacji znaleźli Vasilya i przypuścili szturm na klasztor. Były najemnik musi stawić im czoła – w zniszczeniu bezwzględnej organizacji tkwi jego ostatnia szansa na odkupienie. Redeemer oferuje cały arsenał środków, przy pomocy których możemy radzić sobie z przeciwnikami. Oprócz standardowej broni palnej w rodzaju strzelb i karabinów maszynowych, do dyspozycji mamy wachlarz broni białej, zestaw ciosów pięściami, opcję natychmiastowego zabijania atakami od tyłu, a także możliwość używania do walki elementów środowiska.", ImageName="Redeemer.jpg", ReleaseDate= new DateTime(2015, 11, 11) },
                new Game () {Name="Killer Instinct", PlatformId = 3, Price = 136, IsBestseller = true, Description = "Killer Instinct na XBOX. Trzecia odsłona cyklu zręcznościowych bijatyk zapoczątkowanego w latach 90-tych. Gra powstała w studiu Double Helix Games (Green Lantern: Rise of the Manhunters, MX vs. ATV Reflex). W Killer Instinct gracz wciela się w wybranego przez siebie wojownika i toczy pojedynki przeciwko komputerowym przeciwnikom lub żywym rywalom (możliwa rozgrywka cross-platformowa). Pośród dostępnych postaci znajduje się wielu bohaterów znanych z wcześniejszych odsłon serii (m.in. Thunder, Jago, Sabrewulf czy Glacius), a każdy z nich ma unikalne zdolności i taktykę walki. Rywale stają naprzeciw siebie na dwuwymiarowych arenach z ręcznie rysowanymi tłami. Sama walka jest czysto zręcznościowa i bardzo dynamiczna – gracze mogą wyprowadzać wiele różnych kombinacji ataków, osłon czy specjalnych ciosów. Ciekawym urozmaiceniem są bogate opcje społecznościowe. Killer Instinct oferuje grafikę 2,5D, przy czym wykorzystuje technologię cel-shading, dzięki czemu postaci i lokacje nabrały komiksowego wyglądu.", ImageName="killerInstinct.jpg", ReleaseDate= new DateTime(2015, 11, 11) },
                new Game () {Name="Yesterday Origins", PlatformId = 1, Price = 236, IsBestseller = false, Description = "Yesterday Origins na PS4. Klasyczna przygodówka point-and-click, będąca kontynuacją wydanej w 2012 roku gry Yesterday, opracowaną przez twórców pierwowzoru z hiszpańskiego Pendulo Studios. Podczas zabawy wcielamy się ponownie w postać znanego z poprzedniczki Johna Yesterdaya, a fabuła rozgrywa się dwutorowo i pozwala nam prześledzić wydarzenia mające miejsce zarówno współcześnie, jak i w czasach hiszpańskiej inkwizycji. Pod względem mechaniki, Yesterday Origins stanowi bezpośrednią kontynuację rozwiązań z poprzedniczki, będąc klasyczną przygodówką point-and-click, w której zajmujemy się głównie eksplorowaniem lokacji, prowadzeniem rozmów z postaciami niezależnymi, gromadzeniem przedmiotów oraz rozwiązywaniem zróżnicowanych łamigłówek. W przeciwieństwie do pierwszej odsłony cyklu, gra zrealizowana została w pełnym trójwymiarze, choć twórcom udało się zachować charakterystyczny, kreskówkowy klimat pierwowzoru.", ImageName="YesterdayOrigins.jpg", ReleaseDate= new DateTime(2015, 11, 11) },
                new Game () {Name="Yesterday Origins", PlatformId = 2, Price = 216, IsBestseller = false, Description = "Yesterday Origins na PC. Klasyczna przygodówka point-and-click, będąca kontynuacją wydanej w 2012 roku gry Yesterday, opracowaną przez twórców pierwowzoru z hiszpańskiego Pendulo Studios. Podczas zabawy wcielamy się ponownie w postać znanego z poprzedniczki Johna Yesterdaya, a fabuła rozgrywa się dwutorowo i pozwala nam prześledzić wydarzenia mające miejsce zarówno współcześnie, jak i w czasach hiszpańskiej inkwizycji. Pod względem mechaniki, Yesterday Origins stanowi bezpośrednią kontynuację rozwiązań z poprzedniczki, będąc klasyczną przygodówką point-and-click, w której zajmujemy się głównie eksplorowaniem lokacji, prowadzeniem rozmów z postaciami niezależnymi, gromadzeniem przedmiotów oraz rozwiązywaniem zróżnicowanych łamigłówek. W przeciwieństwie do pierwszej odsłony cyklu, gra zrealizowana została w pełnym trójwymiarze, choć twórcom udało się zachować charakterystyczny, kreskówkowy klimat pierwowzoru.", ImageName="YesterdayOrigins.jpg.", ReleaseDate= new DateTime(2015, 11, 11) },
                new Game () {Name="Yesterday Origins", PlatformId = 3, Price = 266, IsBestseller = false, Description = "Yesterday Origins na XBOX. Klasyczna przygodówka point-and-click, będąca kontynuacją wydanej w 2012 roku gry Yesterday, opracowaną przez twórców pierwowzoru z hiszpańskiego Pendulo Studios. Podczas zabawy wcielamy się ponownie w postać znanego z poprzedniczki Johna Yesterdaya, a fabuła rozgrywa się dwutorowo i pozwala nam prześledzić wydarzenia mające miejsce zarówno współcześnie, jak i w czasach hiszpańskiej inkwizycji. Pod względem mechaniki, Yesterday Origins stanowi bezpośrednią kontynuację rozwiązań z poprzedniczki, będąc klasyczną przygodówką point-and-click, w której zajmujemy się głównie eksplorowaniem lokacji, prowadzeniem rozmów z postaciami niezależnymi, gromadzeniem przedmiotów oraz rozwiązywaniem zróżnicowanych łamigłówek. W przeciwieństwie do pierwszej odsłony cyklu, gra zrealizowana została w pełnym trójwymiarze, choć twórcom udało się zachować charakterystyczny, kreskówkowy klimat pierwowzoru.", ImageName="YesterdayOrigins.jpg", ReleaseDate= new DateTime(2015, 11, 11) },


            };
            foreach (Game game in games)
            {
                context.Games.Add(game);
                context.SaveChanges();                
            }
        }     
            


        
    }
}